routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\RoleController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return redirect()->to('login');
});

Route::get('/register', function () {
    return redirect()->to('login');
});

Route::get('/home', function () {
    return redirect()->to('/admin/home');
});

Route::group([ 'prefix' => 'admin' ,'middleware' => 'auth' ], function () {

    Route::get('/home', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('home');
    Route::resource('roles', RoleController::class,);

    // Users CRUD
    Route::get('users/',
        [
            App\Http\Controllers\Admin\UserController::class,
            'index'
        ])
    ->name('users.index');  
    
    Route::post('users/crear/',
        [
            App\Http\Controllers\Admin\UserController::class,
            'store'
        ])
    ->name('users.store');    
    
    Route::put('users/actualizar/{id}',
        [
            App\Http\Controllers\Admin\UserController::class,
            'update'
        ])
    ->name('users.update');    
    
    Route::delete('users/borrar/{id}',
    [
        App\Http\Controllers\Admin\UserController::class,
        'destroy'
    ])
    ->name('users.destroy');
    
    Route::post('users/importar',
    [
        App\Http\Controllers\Admin\UserController::class,
        'importarUsuarios'
    ])
    ->name('users.import');
        

    

    // motos CRUD
    Route::get('motos/',
    [
        App\Http\Controllers\Admin\MotosController::class,
        'index'
    ])
    ->name('motos.index');

    Route::get('motos/insertar/',
    [
        App\Http\Controllers\Admin\MotosController::class,
        'create'
    ])
    ->name('motos.create');

    Route::get('motos/editar/{id}',
    [
        App\Http\Controllers\Admin\MotosController::class,
        'edit'
    ])
    ->name('motos.edit');

    Route::post('motos/',
    [
        App\Http\Controllers\Admin\MotosController::class,
        'store'
    ])
    ->name('motos.store');

    Route::put('motos/actualizar/{id}',
    [
        App\Http\Controllers\Admin\MotosController::class,
        'update'
    ])
    ->name('motos.update');

    Route::post('motos/borrado/{id}',
    [
        App\Http\Controllers\Admin\MotosController::class,
        'borrado'
    ])
    ->name('motos.borrado');

    Route::delete('motos/borrar/{id}',
    [
        App\Http\Controllers\Admin\MotosController::class,
        'destroy'
    ])
    ->name('motos.destroy');
    
    /**
     * Rutas de automoviñes
     */
    Route::get('autos/',
    [
        App\Http\Controllers\Admin\AutomovilesController::class,
        'index'
    ])
    ->name('autos.index');

    Route::get('autos/insertar/',
    [
        App\Http\Controllers\Admin\AutomovilesController::class,
        'create'
    ])
    ->name('autos.create');

    Route::get('autos/editar/{id}',
    [
        App\Http\Controllers\Admin\AutomovilesController::class,
        'edit'
    ])
    ->name('autos.edit');

    Route::post('autos/',
    [
        App\Http\Controllers\Admin\AutomovilesController::class,
        'store'
    ])
    ->name('autos.store');

    Route::put('autos/actualizar/{id}',
    [
        App\Http\Controllers\Admin\AutomovilesController::class,
        'update'
    ])
    ->name('autos.update');

    Route::delete('autos/borrar/{id}',
    [
        App\Http\Controllers\Admin\AutomovilesController::class,
        'destroy'
    ])
    ->name('autos.destroy');

    Route::post('autos/borrado/{id}',
    [
        App\Http\Controllers\Admin\AutomovilesController::class,
        'borrado'
    ])
    ->name('autos.borrado');


    
    /**
     * Rutas de genericos
     */
    Route::get('genericos/',
    [
        App\Http\Controllers\Admin\ArticulosGenericosController::class,
        'index'
    ])
    ->name('genericos.index');

    Route::get('genericos/insertar/',
    [
        App\Http\Controllers\Admin\ArticulosGenericosController::class,
        'create'
    ])
    ->name('genericos.create');

    Route::get('genericos/editar/{id}',
    [
        App\Http\Controllers\Admin\ArticulosGenericosController::class,
        'edit'
    ])
    ->name('genericos.edit');

    Route::post('genericos/',
    [
        App\Http\Controllers\Admin\ArticulosGenericosController::class,
        'store'
    ])
    ->name('genericos.store');
    
    Route::post('genericos/borrado/{id}',
    [
        App\Http\Controllers\Admin\ArticulosGenericosController::class,
        'borrado'
    ])
    ->name('genericos.borrado');

    Route::put('genericos/actualizar/{id}',
    [
        App\Http\Controllers\Admin\ArticulosGenericosController::class,
        'update'
    ])
    ->name('genericos.update');  

    
    Route::delete('genericos/borrar/{id}',
    [
        App\Http\Controllers\Admin\ArticulosGenericosController::class,
        'destroy'
    ])
    ->name('genericos.destroy');




     // renglones CRUD
     Route::get('renglones/',
     [
         App\Http\Controllers\Admin\RenglonesController::class,
         'index'
     ])
     ->name('renglones.index');   
     
     Route::post('renglones/crear/',
     [
         App\Http\Controllers\Admin\RenglonesController::class,
         'store'
     ])
     ->name('renglones.store');

     Route::put('renglones/actualizar/{id}',
    [
        App\Http\Controllers\Admin\RenglonesController::class,
        'update'
    ])
    ->name('renglones.update');

    Route::delete('renglones/borrar/{id}',
    [
        App\Http\Controllers\Admin\RenglonesController::class,
        'destroy'
    ])
    ->name('renglones.destroy');


    // Articulos CRUD
    Route::get('articulos/',
    [
        App\Http\Controllers\Admin\ArticulosController::class,
        'index'
    ])
    ->name('articulos.index');   
    
    Route::post('articulos/crear/',
    [
        App\Http\Controllers\Admin\ArticulosController::class,
        'store'
    ])
    ->name('articulos.store');

    Route::put('articulos/actualizar/{id}',
   [
       App\Http\Controllers\Admin\ArticulosController::class,
       'update'
   ])
   ->name('articulos.update');

   Route::delete('articulos/borrar/{id}',
   [
       App\Http\Controllers\Admin\ArticulosController::class,
       'destroy'
   ])
   ->name('articulos.destroy');


   // Definicion de Articulos CRUD
   Route::get('fotoMoto/',
   [
       App\Http\Controllers\Admin\MotosController::class,
       'fotoMoto'
   ])
   ->name('fotoMoto.get');   
   
   Route::post('fotoMoto/crear/',
   [
       App\Http\Controllers\Admin\MotosController::class,
       'agregarFotos'
   ])
   ->name('fotoMoto.store');

   Route::put('fotoMoto/actualizar/{id}',
  [
      App\Http\Controllers\Admin\MotosController::class,
      'update'
  ])
  ->name('fotoMoto.update');

  Route::delete('fotoMoto/borrar/',
  [
      App\Http\Controllers\Admin\MotosController::class,
      'eliminarFoto'
  ])
  ->name('fotoMoto.destroy');



  /**
   * Fotos de automovies
   */
  Route::get('fotoAuto/',
  [
      App\Http\Controllers\Admin\AutomovilesController::class,
      'fotoAuto'
  ])
  ->name('fotoAuto.get');   
  
  Route::post('fotoAuto/crear/',
  [
      App\Http\Controllers\Admin\AutomovilesController::class,
      'agregarFotos'
  ])
  ->name('fotoAuto.store');

  Route::put('fotoAuto/actualizar/{id}',
 [
     App\Http\Controllers\Admin\AutomovilesController::class,
     'update'
 ])
 ->name('fotoAuto.update');

 Route::delete('fotoAuto/borrar/',
 [
     App\Http\Controllers\Admin\AutomovilesController::class,
     'eliminarFoto'
 ])
 ->name('fotoAuto.destroy');


 /**
   * Fotos de Genericos
   */
  Route::get('fotoGenerico/',
  [
      App\Http\Controllers\Admin\ArticulosGenericosController::class,
      'fotoGenerico'
  ])
  ->name('fotoGenerico.get');   
  
  Route::post('fotoGenerico/crear/',
  [
      App\Http\Controllers\Admin\ArticulosGenericosController::class,
      'agregarFotos'
  ])
  ->name('fotoGenerico.store');

  Route::put('fotoGenerico/actualizar/{id}',
 [
     App\Http\Controllers\Admin\ArticulosGenericosController::class,
     'update'
 ])
 ->name('fotoGenerico.update');

 Route::delete('fotoGenerico/borrar/',
 [
     App\Http\Controllers\Admin\ArticulosGenericosController::class,
     'eliminarFoto'
 ])
 ->name('fotoGenerico.destroy');

    
    //logout
    Route::get('logout', function(){
        Auth::logout();
        return Redirect::to('login');
    });

    

   

});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Facades\DB;

class RoleController extends Controller
{
    //Crotolador de los rolres de usuario

    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    function __construct()
    {
        $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index','store']]);
        $this->middleware('permission:role-create', ['only' => ['create','store']]);
        $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index(Request $request)
    {
        $roles = Role::orderBy('id','ASC')->paginate(5);
        $permissions = Permission::all();
        
        return view('roles.index',['permissions'=>$permissions, 'roles'=>$roles,], )
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }
    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        $permission = Permission::get();
        return view('roles.create',compact('permission'));
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);
        //var_dump($request->input('permission'));
        //die();
        $role = Role::create(['name' => $request->input('name')]);
        $permissions = Permission::whereIn('id', $request->permission)->get();
        $role->syncPermissions($permissions);
        //$role->syncPermissions($request->input('permission'));
    
        return redirect()->route('roles.index')
                        ->with('success','Role created successfully');
    }

     /**
     * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
            ->where("role_has_permissions.role_id",$id)
            ->get();
            return ([
                'role' => $role,
                'rolePermissions' => $rolePermissions
            ]);
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function edit($id)
    {
        $role = Role::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();
        

        return view('roles.edit',compact('role','permission','rolePermissions'));
    }
    
    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, $id)
    {
        //var_dump($request->input('permission'));        
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);
    
        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();
    
        //$role->syncPermissions($request->input('permission'));
        
        $permissions = $request->input('permission');

        $permissions = array_map(function ($item) {
        return (int)$item;
        }, $permissions);
        
        if (!empty($permissions)){
        $role->syncPermissions($permissions);
        }


        return redirect()->route('roles.index')
                        ->with('success','Role updated successfully');
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function destroy($id)
    {
        DB::table("roles")->where('id',$id)->delete();
        return redirect()->route('roles.index')
                        ->with('success','Role eliminado correctamente');
    }


}

resources/views/roles/index.blade.php
@extends('adminlte::page')

@section('title', 'Roles')

@section('content_header')
    <h1 class="m-0 text-dark">  Roles y permisos</h1>    

@section('content')
    <div class="card">
        <div class="card-header">
          <h1 class="card-title"><i class="fas fa-users"></i> Roles y permisos</h1>
        </div>
        <div class="row">
          <div class="col-md-12 col-xs-12">     
            
             <!-- Enlace para abrir el modal -->
              <br><br>
                <div class="pull-right">
                    @can('role-create')
                        <a class="btn btn-success"  data-toggle="modal" data-target="#RolesInsertModal">Nuevo Rol</a>
                    @endcan
                </div>
                
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
          </div>
      </div>
      <br>

        
    <div class="col-12 table-responsive">
        <table class="table table-bordered">
            <tr>
                <th>Nro</th>
                <th>Name</th>
                <th width="280px">Action</th>
            </tr>
            @foreach ($roles as $key => $role)            
            <tr>
                <td>{{ $role->id }}</td>
                <td>{{ $role->name }}</td>
                <td>                
                @can('role-edit')
                <a class="btn btn-primary" data-toggle="modal"  data-target="#updateRoleModal{{ $role->id }}" >Editar</a>
                @endcan
                @can('role-delete')
                {!! Form::open(['method' => 'DELETE','route' => ['roles.destroy',
                $role->id],'style'=>'display:inline']) !!}
                {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                {!! Form::close() !!}
                @endcan
                </td>
            </tr>            
            @include('roles/updateRole')
            @endforeach
        </table>
    </div>
        

      {!! $roles->render() !!}
     <p class="text-center text-primary"><small>lista de roles de Usuarios</small></p>

     @include('roles/insertRole')
@endsection
<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<script type="text/javascript">

</script>
@stop

resources/views/roles/insertRole.blade.php
<div id="RolesInsertModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Contenido del modal -->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
              <h3><strong><p>Agregar Nuevo Rol</p></strong></h3>
              {!! Form::open(array('route' => 'roles.store','method'=>'POST')) !!}
                <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <strong>Name:</strong>
                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <strong>Permission:</strong>
                <br/>
                @foreach($permissions as $value)
                <label>{{ Form::checkbox('permission[]', $value->id, false, array('class' => 'name')) }}
                {{ $value->name }}</label>
                <br/>
                @endforeach
                </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div><!--content-->
    </div><!--diañog-->
</div><!--Modal-->

resources/views/roles/showRole.blade.php
<div id="RolesShowModal{{$role->id}}" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Contenido del modal -->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
              <h3><strong><p>Listado de roles</p></strong></h3>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                        <strong>Name:</strong>
                        {{ $role->name }}
                    </div>
                </div>
                
                <form method="post" action="{{ route('roles.show',$role->id) }}">
                @csrf
                @method('POST')
                <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Permissions:</strong>
                        </div>
                    </div>
                </form>
                
            </div><!-- Modal body-->
        </div><!--Modal content-->
    </div><!--Modal dialog-->
</div><!--Form Modal-->

resources/views/roles/updateRole.blade.php
<div class="modal fade" tabindex="-1" role="dialog" id="updateRoleModal{{$role->id}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Actualizar Role</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {!! Form::model($role, ['method' => 'PATCH','route' => ['roles.update', $role->id]]) !!}
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Name:</strong>
                            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Permission:</strong>
                            <br/>
                            @php
                                //var_dump($permissions[4]->id);
                               
                                $rolPermissions = array('rolpermissions'=>$role->permissions,);
                                $listaPermisos = array();
                                foreach($rolPermissions['rolpermissions'] as $permi=>$value){
                                    $listaPermisos[]=$value->id;
                                }
                               
                            @endphp
                            @foreach($permissions as $permission)
                                    
                                    <label>{{ Form::checkbox('permission[]', $permission->id, in_array($permission->id, $listaPermisos, true) ? true : false, array('class' => 'name')) }}
                                    {{ $permission->name }}</label>
                                
                                <br/>                               
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Actualizar</button>
                {!! Form::close() !!}
            </div><!--body-->     
        </div>
    </div>
</div>